In [2]:
import numpy as np
import pandas as pd
import torch

train_x = pd.read_excel('F:\\gitworkspace\\python\\pop-cnn\\trainingset.xlsx', header = None)

train_x

,0,1,2,3,4,5,6,7,8,9,...,240,241,242,243,244,245,246,247,248,249
0,-1.20000,-1.20000,-1.20000,-0.2000,2.8000,3.800,2.800,1.800,0.800,0.800,...,6.800,7.800,6.800,6.800,6.800,6.800,6.800,6.800,6.800,6.800
1,-2.33330,-1.33330,-2.33330,-1.3333,8.6667,14.667,15.667,15.667,14.667,13.667,...,37.667,37.667,37.667,37.667,37.667,37.667,37.667,36.667,36.667,36.667
2,-3.62500,-3.62500,-3.62500,-0.6250,46.3750,48.375,38.375,31.375,25.375,21.375,...,48.375,48.375,48.375,47.375,47.375,47.375,47.375,46.375,47.375,46.375
3,-0.85714,-0.85714,-0.85714,5.1429,24.1430,24.143,20.143,17.143,14.143,12.143,...,27.143,26.143,26.143,26.143,26.143,26.143,26.143,26.143,26.143,26.143
4,-2.57140,-1.57140,-1.57140,10.4290,33.4290,36.429,36.429,36.429,34.429,31.429,...,71.429,70.429,70.429,70.429,70.429,69.429,68.429,69.429,68.429,68.429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803,-1.30000,-1.30000,-0.30000,-0.3000,-0.3000,55.700,345.700,831.700,1319.700,1839.700,...,147.700,146.700,145.700,144.700,144.700,143.700,142.700,141.700,140.700,139.700
3804,-0.90000,0.10000,0.10000,0.1000,0.1000,6.100,3431.100,32343.000,32675.000,32675.000,...,388.100,385.100,383.100,380.100,378.100,375.100,372.100,370.100,368.100,365.100
3805,-1.40000,-0.40000,-0.40000,0.6000,0.6000,1.600,45.600,214.600,548.600,1116.600,...,313.600,311.600,309.600,307.600,305.600,303.600,302.600,300.600,298.600,296.600
3806,0.00000,0.00000,0.00000,0.0000,0.0000,0.000,0.000,4.000,39.000,222.000,...,168.000,167.000,165.000,164.000,164.000,163.000,161.000,161.000,160.000,159.000
3807,0.00000,0.00000,0.00000,0.0000,0.0000,0.000,2.000,17250.000,32510.000,32510.000,...,1010.000,1003.000,996.000,989.000,982.000,975.000,969.000,962.000,956.000,949.000

In [2]:
train_x = train_x.fillna(method='ffill')
    
train_x

In [3]:
np.save('trainingset.npy', train_x)

train_x = np.load('trainingset.npy')

train_x

In [4]:
def Normlize(Z):
    Zmax, Zmin = Z.max(axis=1), Z.min(axis=1)
    print(Zmax)
    print(Zmin)
    Zmean = Z.mean(axis=1)
    print(Zmean)
    Zmax, Zmin = Zmax.reshape(-1, 1), Zmin.reshape(-1, 1)
    print(Zmax)
    print(Zmin)
    Zmean = Zmean.reshape(-1, 1)
    Z = (Z - Zmean) / (Zmax - Zmin)
    return Z

train_x_Normed = Normlize(train_x)

train_x_Normed

In [9]:
train_x = torch.from_numpy(train_x_Normed).type(torch.cuda.FloatTensor)

train_x

In [ ]:
train_x = train_x.view(238, 1, 16, 250)

train_x